version: '3.8'
services:
  db:
    image: postgres:12-alpine
    container_name: myapp-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - trackbee
    ports:
      - '${DB_PORT}:5432'

  redis:
    image: redis:6-alpine
    container_name: myapp-redis
    networks:
      - trackbee
    ports:
      - '${REDIS_PORT}:6379'

networks:
  trackbee:
    driver: bridge
